import './globals.css'
import { Inter } from 'next/font/google'
import CopyWrite from '@/components/ui/copywrite'
import Footer from '@/components/ui/footer'
import Header from '@/components/ui/header'
import { Toast } from '@/components/ui/toast'
import { Toaster } from '@/components/ui/toaster'
import Providers from '@/components/Provider'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body className={inter.className}>
      <Providers>  
        <Header />
        {children}
        <Toaster />
        <Footer />
        <CopyWrite />
      </Providers>
      </body>
    </html>
    </ClerkProvider>
  )
}
